//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using static Unity.Mathematics.math;
using Burst.Compiler.IL.Tests;

namespace Unity.Mathematics.Tests
{
    [TestFixture]
    public class TestFix64p2
    {
        [TestCompiler]
        public static void fix64p2_zero()
        {
            TestUtils.AreEqual(fix64p2.zero.x, fix64p.zero);
            TestUtils.AreEqual(fix64p2.zero.y, fix64p.zero);
        }

        [TestCompiler]
        public static void fix64p2_constructor()
        {
            fix64p2 a = new fix64p2(new fix64p(1f), new fix64p(2f));
            TestUtils.AreEqual(a.x, new fix64p(1f));
            TestUtils.AreEqual(a.y, new fix64p(2f));
        }

        [TestCompiler]
        public static void fix64p2_scalar_constructor()
        {
            fix64p2 a = new fix64p2(new fix64p(17.0f));
            TestUtils.AreEqual(a.x, new fix64p(17.0f));
            TestUtils.AreEqual(a.y, new fix64p(17.0f));
        }

        [TestCompiler]
        public static void fix64p2_static_constructor()
        {
            fix64p2 a = fix64p2(new fix64p(1f), new fix64p(2f));
            TestUtils.AreEqual(a.x, new fix64p(1f));
            TestUtils.AreEqual(a.y, new fix64p(2f));
        }

        [TestCompiler]
        public static void fix64p2_static_scalar_constructor()
        {
            fix64p2 a = fix64p2(new fix64p(17.0f));
            TestUtils.AreEqual(a.x, new fix64p(17.0f));
            TestUtils.AreEqual(a.y, new fix64p(17.0f));
        }

        [TestCompiler]
        public static void fix64p2_operator_equal_wide_wide()
        {
            fix64p2 a0 = fix64p2(new fix64p(-135.18924f), new fix64p(-49.0941162f));
            fix64p2 b0 = fix64p2(new fix64p(-220.014648f), new fix64p(66.98004f));
            bool2 r0 = bool2(false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            fix64p2 a1 = fix64p2(new fix64p(169.129822f), new fix64p(240.8053f));
            fix64p2 b1 = fix64p2(new fix64p(499.2016f), new fix64p(-371.1131f));
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            fix64p2 a2 = fix64p2(new fix64p(314.7392f), new fix64p(442.393f));
            fix64p2 b2 = fix64p2(new fix64p(208.448669f), new fix64p(390.8037f));
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            fix64p2 a3 = fix64p2(new fix64p(177.924438f), new fix64p(335.5334f));
            fix64p2 b3 = fix64p2(new fix64p(-72.44382f), new fix64p(362.97644f));
            bool2 r3 = bool2(false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void fix64p2_operator_equal_wide_scalar()
        {
            fix64p2 a0 = fix64p2(new fix64p(65.6712f), new fix64p(404.415527f));
            fix64p b0 = (new fix64p(-155.815765f));
            bool2 r0 = bool2(false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            fix64p2 a1 = fix64p2(new fix64p(-269.730164f), new fix64p(152.9945f));
            fix64p b1 = (new fix64p(83.6306152f));
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            fix64p2 a2 = fix64p2(new fix64p(-155.868286f), new fix64p(386.365173f));
            fix64p b2 = (new fix64p(314.671265f));
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            fix64p2 a3 = fix64p2(new fix64p(290.04895f), new fix64p(-65.66748f));
            fix64p b3 = (new fix64p(-132.6352f));
            bool2 r3 = bool2(false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void fix64p2_operator_equal_scalar_wide()
        {
            fix64p a0 = (new fix64p(36.38391f));
            fix64p2 b0 = fix64p2(new fix64p(-400.4892f), new fix64p(-71.2868347f));
            bool2 r0 = bool2(false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            fix64p a1 = (new fix64p(156.978088f));
            fix64p2 b1 = fix64p2(new fix64p(-225.238739f), new fix64p(499.141785f));
            bool2 r1 = bool2(false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            fix64p a2 = (new fix64p(-211.979919f));
            fix64p2 b2 = fix64p2(new fix64p(428.311951f), new fix64p(-489.501343f));
            bool2 r2 = bool2(false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            fix64p a3 = (new fix64p(-5.691559f));
            fix64p2 b3 = fix64p2(new fix64p(-30.8659363f), new fix64p(-362.9831f));
            bool2 r3 = bool2(false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void fix64p2_operator_not_equal_wide_wide()
        {
            fix64p2 a0 = fix64p2(new fix64p(279.994141f), new fix64p(-43.34201f));
            fix64p2 b0 = fix64p2(new fix64p(-460.9121f), new fix64p(-476.009033f));
            bool2 r0 = bool2(true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            fix64p2 a1 = fix64p2(new fix64p(-465.724731f), new fix64p(317.466553f));
            fix64p2 b1 = fix64p2(new fix64p(468.1364f), new fix64p(-341.012543f));
            bool2 r1 = bool2(true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            fix64p2 a2 = fix64p2(new fix64p(85.7149658f), new fix64p(360.8905f));
            fix64p2 b2 = fix64p2(new fix64p(-62.65805f), new fix64p(-458.801666f));
            bool2 r2 = bool2(true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            fix64p2 a3 = fix64p2(new fix64p(366.081543f), new fix64p(154.542847f));
            fix64p2 b3 = fix64p2(new fix64p(-457.730225f), new fix64p(-59.5232544f));
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void fix64p2_operator_not_equal_wide_scalar()
        {
            fix64p2 a0 = fix64p2(new fix64p(-155.4411f), new fix64p(-19.4266052f));
            fix64p b0 = (new fix64p(-393.413544f));
            bool2 r0 = bool2(true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            fix64p2 a1 = fix64p2(new fix64p(174.633057f), new fix64p(59.177063f));
            fix64p b1 = (new fix64p(507.920715f));
            bool2 r1 = bool2(true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            fix64p2 a2 = fix64p2(new fix64p(171.151489f), new fix64p(-398.176849f));
            fix64p b2 = (new fix64p(-58.92328f));
            bool2 r2 = bool2(true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            fix64p2 a3 = fix64p2(new fix64p(492.20105f), new fix64p(270.341f));
            fix64p b3 = (new fix64p(-165.241516f));
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void fix64p2_operator_not_equal_scalar_wide()
        {
            fix64p a0 = (new fix64p(478.353149f));
            fix64p2 b0 = fix64p2(new fix64p(459.553223f), new fix64p(436.453247f));
            bool2 r0 = bool2(true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            fix64p a1 = (new fix64p(-488.714172f));
            fix64p2 b1 = fix64p2(new fix64p(392.767944f), new fix64p(-266.736633f));
            bool2 r1 = bool2(true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            fix64p a2 = (new fix64p(338.557861f));
            fix64p2 b2 = fix64p2(new fix64p(-338.100128f), new fix64p(-152.314545f));
            bool2 r2 = bool2(true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            fix64p a3 = (new fix64p(-452.820679f));
            fix64p2 b3 = fix64p2(new fix64p(209.439331f), new fix64p(50.10797f));
            bool2 r3 = bool2(true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void fix64p2_shuffle_result_1()
        {
            fix64p2 a = fix64p2(new fix64p(0f), new fix64p(1f));
            fix64p2 b = fix64p2(new fix64p(0f), new fix64p(1f));

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX), (new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY), (new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX), (new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY), (new fix64p(1f)));
        }

        [TestCompiler]
        public static void fix64p2_shuffle_result_2()
        {
            fix64p2 a = fix64p2(new fix64p(0f), new fix64p(1f));
            fix64p2 b = fix64p2(new fix64p(0f), new fix64p(1f));

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftX), fix64p2(new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.LeftX), fix64p2(new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftX), fix64p2(new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX), fix64p2(new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftY), fix64p2(new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.LeftY), fix64p2(new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftY), fix64p2(new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftY), fix64p2(new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.RightX), fix64p2(new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.RightX), fix64p2(new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX), fix64p2(new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX), fix64p2(new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.RightY), fix64p2(new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.RightY), fix64p2(new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightY), fix64p2(new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightY), fix64p2(new fix64p(1f), new fix64p(1f)));
        }

        [TestCompiler]
        public static void fix64p2_shuffle_result_3()
        {
            fix64p2 a = fix64p2(new fix64p(0f), new fix64p(1f));
            fix64p2 b = fix64p2(new fix64p(0f), new fix64p(1f));

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightY, ShuffleComponent.RightY), fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftX, ShuffleComponent.RightX), fix64p3(new fix64p(0f), new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftY, ShuffleComponent.RightY), fix64p3(new fix64p(1f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.LeftY, ShuffleComponent.LeftY), fix64p3(new fix64p(1f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.RightY), fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.RightY, ShuffleComponent.RightY), fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.RightY), fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightY, ShuffleComponent.LeftX), fix64p3(new fix64p(1f), new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.RightY), fix64p3(new fix64p(0f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.LeftX), fix64p3(new fix64p(0f), new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.LeftY), fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX, ShuffleComponent.RightY), fix64p3(new fix64p(1f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.LeftY), fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX, ShuffleComponent.RightX), fix64p3(new fix64p(1f), new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.RightY), fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftY, ShuffleComponent.LeftY), fix64p3(new fix64p(1f), new fix64p(1f), new fix64p(1f)));
        }

        [TestCompiler]
        public static void fix64p2_shuffle_result_4()
        {
            fix64p2 a = fix64p2(new fix64p(0f), new fix64p(1f));
            fix64p2 b = fix64p2(new fix64p(0f), new fix64p(1f));

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.RightX), fix64p4(new fix64p(0f), new fix64p(0f), new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.LeftX, ShuffleComponent.RightY), fix64p4(new fix64p(0f), new fix64p(1f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX, ShuffleComponent.RightY, ShuffleComponent.RightX), fix64p4(new fix64p(1f), new fix64p(0f), new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftX, ShuffleComponent.RightY, ShuffleComponent.RightY), fix64p4(new fix64p(0f), new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.RightX), fix64p4(new fix64p(0f), new fix64p(1f), new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.RightY, ShuffleComponent.LeftY), fix64p4(new fix64p(1f), new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.RightY, ShuffleComponent.LeftX), fix64p4(new fix64p(0f), new fix64p(0f), new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.LeftX, ShuffleComponent.RightY), fix64p4(new fix64p(0f), new fix64p(0f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.RightX, ShuffleComponent.LeftY), fix64p4(new fix64p(0f), new fix64p(1f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.RightY, ShuffleComponent.RightY), fix64p4(new fix64p(0f), new fix64p(1f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightY, ShuffleComponent.RightY, ShuffleComponent.LeftY), fix64p4(new fix64p(1f), new fix64p(1f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.LeftY), fix64p4(new fix64p(0f), new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.LeftX, ShuffleComponent.LeftX), fix64p4(new fix64p(1f), new fix64p(0f), new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.RightY), fix64p4(new fix64p(0f), new fix64p(0f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.RightY), fix64p4(new fix64p(0f), new fix64p(1f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftX, ShuffleComponent.LeftX, ShuffleComponent.LeftX), fix64p4(new fix64p(0f), new fix64p(0f), new fix64p(0f), new fix64p(0f)));
        }


    }
}
