//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using NUnit.Framework;
using static Unity.Mathematics.math;
using Burst.Compiler.IL.Tests;

namespace Unity.Mathematics.Tests
{
    [TestFixture]
    public class TestFix64p3
    {
        [TestCompiler]
        public static void fix64p3_zero()
        {
            TestUtils.AreEqual(fix64p3.zero.x, fix64p.zero);
            TestUtils.AreEqual(fix64p3.zero.y, fix64p.zero);
            TestUtils.AreEqual(fix64p3.zero.z, fix64p.zero);
        }

        [TestCompiler]
        public static void fix64p3_constructor()
        {
            fix64p3 a = new fix64p3(new fix64p(1f), new fix64p(2f), new fix64p(3f));
            TestUtils.AreEqual(a.x, new fix64p(1f));
            TestUtils.AreEqual(a.y, new fix64p(2f));
            TestUtils.AreEqual(a.z, new fix64p(3f));
        }

        [TestCompiler]
        public static void fix64p3_scalar_constructor()
        {
            fix64p3 a = new fix64p3(new fix64p(17.0f));
            TestUtils.AreEqual(a.x, new fix64p(17.0f));
            TestUtils.AreEqual(a.y, new fix64p(17.0f));
            TestUtils.AreEqual(a.z, new fix64p(17.0f));
        }

        [TestCompiler]
        public static void fix64p3_static_constructor()
        {
            fix64p3 a = fix64p3(new fix64p(1f), new fix64p(2f), new fix64p(3f));
            TestUtils.AreEqual(a.x, new fix64p(1f));
            TestUtils.AreEqual(a.y, new fix64p(2f));
            TestUtils.AreEqual(a.z, new fix64p(3f));
        }

        [TestCompiler]
        public static void fix64p3_static_scalar_constructor()
        {
            fix64p3 a = fix64p3(new fix64p(17.0f));
            TestUtils.AreEqual(a.x, new fix64p(17.0f));
            TestUtils.AreEqual(a.y, new fix64p(17.0f));
            TestUtils.AreEqual(a.z, new fix64p(17.0f));
        }

        [TestCompiler]
        public static void fix64p3_operator_equal_wide_wide()
        {
            fix64p3 a0 = fix64p3(new fix64p(-135.18924f), new fix64p(-49.0941162f), new fix64p(169.129822f));
            fix64p3 b0 = fix64p3(new fix64p(-220.014648f), new fix64p(66.98004f), new fix64p(499.2016f));
            bool3 r0 = bool3(false, false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            fix64p3 a1 = fix64p3(new fix64p(240.8053f), new fix64p(314.7392f), new fix64p(442.393f));
            fix64p3 b1 = fix64p3(new fix64p(-371.1131f), new fix64p(208.448669f), new fix64p(390.8037f));
            bool3 r1 = bool3(false, false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            fix64p3 a2 = fix64p3(new fix64p(177.924438f), new fix64p(335.5334f), new fix64p(168.15448f));
            fix64p3 b2 = fix64p3(new fix64p(-72.44382f), new fix64p(362.97644f), new fix64p(194.678345f));
            bool3 r2 = bool3(false, false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            fix64p3 a3 = fix64p3(new fix64p(350.729553f), new fix64p(367.178467f), new fix64p(46.9414673f));
            fix64p3 b3 = fix64p3(new fix64p(471.644836f), new fix64p(-404.044678f), new fix64p(-144.696747f));
            bool3 r3 = bool3(false, false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void fix64p3_operator_equal_wide_scalar()
        {
            fix64p3 a0 = fix64p3(new fix64p(65.6712f), new fix64p(404.415527f), new fix64p(-269.730164f));
            fix64p b0 = (new fix64p(-155.815765f));
            bool3 r0 = bool3(false, false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            fix64p3 a1 = fix64p3(new fix64p(83.6306152f), new fix64p(-155.868286f), new fix64p(314.671265f));
            fix64p b1 = (new fix64p(152.9945f));
            bool3 r1 = bool3(false, false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            fix64p3 a2 = fix64p3(new fix64p(386.365173f), new fix64p(-132.6352f), new fix64p(-65.66748f));
            fix64p b2 = (new fix64p(290.04895f));
            bool3 r2 = bool3(false, false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            fix64p3 a3 = fix64p3(new fix64p(-69.68326f), new fix64p(186.845215f), new fix64p(-232.895691f));
            fix64p b3 = (new fix64p(-191.190765f));
            bool3 r3 = bool3(false, false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void fix64p3_operator_equal_scalar_wide()
        {
            fix64p a0 = (new fix64p(36.38391f));
            fix64p3 b0 = fix64p3(new fix64p(-400.4892f), new fix64p(-71.2868347f), new fix64p(156.978088f));
            bool3 r0 = bool3(false, false, false);
            TestUtils.AreEqual(a0 == b0, r0);

            fix64p a1 = (new fix64p(-225.238739f));
            fix64p3 b1 = fix64p3(new fix64p(499.141785f), new fix64p(-211.979919f), new fix64p(428.311951f));
            bool3 r1 = bool3(false, false, false);
            TestUtils.AreEqual(a1 == b1, r1);

            fix64p a2 = (new fix64p(-489.501343f));
            fix64p3 b2 = fix64p3(new fix64p(-5.691559f), new fix64p(-30.8659363f), new fix64p(-362.9831f));
            bool3 r2 = bool3(false, false, false);
            TestUtils.AreEqual(a2 == b2, r2);

            fix64p a3 = (new fix64p(184.503174f));
            fix64p3 b3 = fix64p3(new fix64p(-160.470612f), new fix64p(316.668823f), new fix64p(390.369263f));
            bool3 r3 = bool3(false, false, false);
            TestUtils.AreEqual(a3 == b3, r3);
        }

        [TestCompiler]
        public static void fix64p3_operator_not_equal_wide_wide()
        {
            fix64p3 a0 = fix64p3(new fix64p(279.994141f), new fix64p(-43.34201f), new fix64p(-465.724731f));
            fix64p3 b0 = fix64p3(new fix64p(-460.9121f), new fix64p(-476.009033f), new fix64p(468.1364f));
            bool3 r0 = bool3(true, true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            fix64p3 a1 = fix64p3(new fix64p(317.466553f), new fix64p(85.7149658f), new fix64p(360.8905f));
            fix64p3 b1 = fix64p3(new fix64p(-341.012543f), new fix64p(-62.65805f), new fix64p(-458.801666f));
            bool3 r1 = bool3(true, true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            fix64p3 a2 = fix64p3(new fix64p(366.081543f), new fix64p(154.542847f), new fix64p(332.4262f));
            fix64p3 b2 = fix64p3(new fix64p(-457.730225f), new fix64p(-59.5232544f), new fix64p(3.024231f));
            bool3 r2 = bool3(true, true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            fix64p3 a3 = fix64p3(new fix64p(397.11322f), new fix64p(-431.374969f), new fix64p(489.0108f));
            fix64p3 b3 = fix64p3(new fix64p(155.812744f), new fix64p(-19.8399048f), new fix64p(-6.01693726f));
            bool3 r3 = bool3(true, true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void fix64p3_operator_not_equal_wide_scalar()
        {
            fix64p3 a0 = fix64p3(new fix64p(-155.4411f), new fix64p(-19.4266052f), new fix64p(174.633057f));
            fix64p b0 = (new fix64p(-393.413544f));
            bool3 r0 = bool3(true, true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            fix64p3 a1 = fix64p3(new fix64p(507.920715f), new fix64p(171.151489f), new fix64p(-58.92328f));
            fix64p b1 = (new fix64p(59.177063f));
            bool3 r1 = bool3(true, true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            fix64p3 a2 = fix64p3(new fix64p(-398.176849f), new fix64p(-165.241516f), new fix64p(270.341f));
            fix64p b2 = (new fix64p(492.20105f));
            bool3 r2 = bool3(true, true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            fix64p3 a3 = fix64p3(new fix64p(-380.243256f), new fix64p(-134.345459f), new fix64p(458.400452f));
            fix64p b3 = (new fix64p(501.899048f));
            bool3 r3 = bool3(true, true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void fix64p3_operator_not_equal_scalar_wide()
        {
            fix64p a0 = (new fix64p(478.353149f));
            fix64p3 b0 = fix64p3(new fix64p(459.553223f), new fix64p(436.453247f), new fix64p(-488.714172f));
            bool3 r0 = bool3(true, true, true);
            TestUtils.AreEqual(a0 != b0, r0);

            fix64p a1 = (new fix64p(392.767944f));
            fix64p3 b1 = fix64p3(new fix64p(-266.736633f), new fix64p(338.557861f), new fix64p(-338.100128f));
            bool3 r1 = bool3(true, true, true);
            TestUtils.AreEqual(a1 != b1, r1);

            fix64p a2 = (new fix64p(-152.314545f));
            fix64p3 b2 = fix64p3(new fix64p(-452.820679f), new fix64p(209.439331f), new fix64p(50.10797f));
            bool3 r2 = bool3(true, true, true);
            TestUtils.AreEqual(a2 != b2, r2);

            fix64p a3 = (new fix64p(372.4344f));
            fix64p3 b3 = fix64p3(new fix64p(-488.0213f), new fix64p(489.740784f), new fix64p(270.4001f));
            bool3 r3 = bool3(true, true, true);
            TestUtils.AreEqual(a3 != b3, r3);
        }

        [TestCompiler]
        public static void fix64p3_shuffle_result_1()
        {
            fix64p3 a = fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(2f));
            fix64p3 b = fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(2f));

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX), (new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY), (new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftZ), (new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX), (new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY), (new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ), (new fix64p(2f)));
        }

        [TestCompiler]
        public static void fix64p3_shuffle_result_2()
        {
            fix64p3 a = fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(2f));
            fix64p3 b = fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(2f));

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightY), fix64p2(new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX), fix64p2(new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.RightX), fix64p2(new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ, ShuffleComponent.LeftZ), fix64p2(new fix64p(2f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ, ShuffleComponent.LeftY), fix64p2(new fix64p(2f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.LeftZ), fix64p2(new fix64p(1f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftZ), fix64p2(new fix64p(0f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ, ShuffleComponent.LeftX), fix64p2(new fix64p(2f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ, ShuffleComponent.RightZ), fix64p2(new fix64p(2f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftY), fix64p2(new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightZ), fix64p2(new fix64p(1f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ, ShuffleComponent.LeftX), fix64p2(new fix64p(2f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX), fix64p2(new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ, ShuffleComponent.RightY), fix64p2(new fix64p(2f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftX), fix64p2(new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.LeftZ), fix64p2(new fix64p(1f), new fix64p(2f)));
        }

        [TestCompiler]
        public static void fix64p3_shuffle_result_3()
        {
            fix64p3 a = fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(2f));
            fix64p3 b = fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(2f));

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.RightZ, ShuffleComponent.RightX), fix64p3(new fix64p(1f), new fix64p(2f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.LeftZ), fix64p3(new fix64p(1f), new fix64p(0f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftZ, ShuffleComponent.RightZ, ShuffleComponent.RightX), fix64p3(new fix64p(2f), new fix64p(2f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.LeftY), fix64p3(new fix64p(1f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ, ShuffleComponent.RightY, ShuffleComponent.LeftZ), fix64p3(new fix64p(2f), new fix64p(1f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftZ, ShuffleComponent.LeftX, ShuffleComponent.LeftY), fix64p3(new fix64p(2f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftZ, ShuffleComponent.RightY, ShuffleComponent.RightX), fix64p3(new fix64p(2f), new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftZ, ShuffleComponent.LeftY, ShuffleComponent.RightZ), fix64p3(new fix64p(2f), new fix64p(1f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightY, ShuffleComponent.RightZ), fix64p3(new fix64p(1f), new fix64p(1f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX, ShuffleComponent.LeftY), fix64p3(new fix64p(1f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ, ShuffleComponent.RightZ, ShuffleComponent.LeftX), fix64p3(new fix64p(2f), new fix64p(2f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ, ShuffleComponent.LeftY, ShuffleComponent.RightX), fix64p3(new fix64p(2f), new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftY, ShuffleComponent.RightZ), fix64p3(new fix64p(1f), new fix64p(1f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftZ, ShuffleComponent.RightX, ShuffleComponent.RightY), fix64p3(new fix64p(2f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.RightY), fix64p3(new fix64p(1f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.RightZ), fix64p3(new fix64p(1f), new fix64p(0f), new fix64p(2f)));
        }

        [TestCompiler]
        public static void fix64p3_shuffle_result_4()
        {
            fix64p3 a = fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(2f));
            fix64p3 b = fix64p3(new fix64p(0f), new fix64p(1f), new fix64p(2f));

            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.LeftZ, ShuffleComponent.RightX, ShuffleComponent.LeftY), fix64p4(new fix64p(1f), new fix64p(2f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftZ, ShuffleComponent.RightZ, ShuffleComponent.RightY), fix64p4(new fix64p(1f), new fix64p(2f), new fix64p(2f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightY, ShuffleComponent.RightZ, ShuffleComponent.LeftY), fix64p4(new fix64p(1f), new fix64p(1f), new fix64p(2f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.LeftY), fix64p4(new fix64p(0f), new fix64p(0f), new fix64p(1f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftY, ShuffleComponent.LeftY, ShuffleComponent.LeftX), fix64p4(new fix64p(1f), new fix64p(1f), new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightY, ShuffleComponent.RightX, ShuffleComponent.RightZ), fix64p4(new fix64p(0f), new fix64p(1f), new fix64p(0f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.RightZ, ShuffleComponent.LeftX, ShuffleComponent.RightZ), fix64p4(new fix64p(1f), new fix64p(2f), new fix64p(0f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.LeftX, ShuffleComponent.LeftX, ShuffleComponent.LeftX), fix64p4(new fix64p(1f), new fix64p(0f), new fix64p(0f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.RightZ, ShuffleComponent.LeftZ, ShuffleComponent.LeftX), fix64p4(new fix64p(0f), new fix64p(2f), new fix64p(2f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightY, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.RightX), fix64p4(new fix64p(1f), new fix64p(0f), new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftX, ShuffleComponent.LeftZ, ShuffleComponent.RightZ, ShuffleComponent.LeftX), fix64p4(new fix64p(0f), new fix64p(2f), new fix64p(2f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftY, ShuffleComponent.RightY, ShuffleComponent.RightZ, ShuffleComponent.RightZ), fix64p4(new fix64p(1f), new fix64p(1f), new fix64p(2f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftZ, ShuffleComponent.RightX, ShuffleComponent.LeftY, ShuffleComponent.RightX), fix64p4(new fix64p(2f), new fix64p(0f), new fix64p(1f), new fix64p(0f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightX, ShuffleComponent.LeftX, ShuffleComponent.LeftY, ShuffleComponent.LeftZ), fix64p4(new fix64p(0f), new fix64p(0f), new fix64p(1f), new fix64p(2f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.RightZ, ShuffleComponent.RightX, ShuffleComponent.LeftX, ShuffleComponent.RightY), fix64p4(new fix64p(2f), new fix64p(0f), new fix64p(0f), new fix64p(1f)));
            TestUtils.AreEqual(shuffle(a, b, ShuffleComponent.LeftZ, ShuffleComponent.RightZ, ShuffleComponent.LeftX, ShuffleComponent.RightY), fix64p4(new fix64p(2f), new fix64p(2f), new fix64p(0f), new fix64p(1f)));
        }


    }
}
