//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;
using System.Diagnostics;

#pragma warning disable 0660, 0661

namespace Unity.Mathematics
{
    [DebuggerTypeProxy(typeof(fix64p3.DebuggerProxy))]
    [System.Serializable]
    public partial struct fix64p3 : System.IEquatable<fix64p3>, IFormattable
    {
        public fix64p x;
        public fix64p y;
        public fix64p z;

        /// <summary>fix64p3 zero value.</summary>
        public static readonly fix64p3 zero;

        /// <summary>Constructs a fix64p3 vector from three fix64p values.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p3(fix64p x, fix64p y, fix64p z)
        { 
            this.x = x;
            this.y = y;
            this.z = z;
        }

        /// <summary>Constructs a fix64p3 vector from a fix64p value and a fix64p2 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p3(fix64p x, fix64p2 yz)
        { 
            this.x = x;
            this.y = yz.x;
            this.z = yz.y;
        }

        /// <summary>Constructs a fix64p3 vector from a fix64p2 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p3(fix64p2 xy, fix64p z)
        { 
            this.x = xy.x;
            this.y = xy.y;
            this.z = z;
        }

        /// <summary>Constructs a fix64p3 vector from a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p3(fix64p3 xyz)
        { 
            this.x = xyz.x;
            this.y = xyz.y;
            this.z = xyz.z;
        }

        /// <summary>Constructs a fix64p3 vector from a single fix64p value by assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p3(fix64p v)
        {
            this.x = v;
            this.y = v;
            this.z = v;
        }


        /// <summary>Implicitly converts a single fix64p value to a fix64p3 vector by assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator fix64p3(fix64p v) { return new fix64p3(v); }


        /// <summary>Returns the result of a componentwise multiplication operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator * (fix64p3 lhs, fix64p3 rhs) { return new fix64p3 (lhs.x * rhs.x, lhs.y * rhs.y, lhs.z * rhs.z); }

        /// <summary>Returns the result of a componentwise multiplication operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator * (fix64p3 lhs, fix64p rhs) { return new fix64p3 (lhs.x * rhs, lhs.y * rhs, lhs.z * rhs); }

        /// <summary>Returns the result of a componentwise multiplication operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator * (fix64p lhs, fix64p3 rhs) { return new fix64p3 (lhs * rhs.x, lhs * rhs.y, lhs * rhs.z); }


        /// <summary>Returns the result of a componentwise addition operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator + (fix64p3 lhs, fix64p3 rhs) { return new fix64p3 (lhs.x + rhs.x, lhs.y + rhs.y, lhs.z + rhs.z); }

        /// <summary>Returns the result of a componentwise addition operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator + (fix64p3 lhs, fix64p rhs) { return new fix64p3 (lhs.x + rhs, lhs.y + rhs, lhs.z + rhs); }

        /// <summary>Returns the result of a componentwise addition operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator + (fix64p lhs, fix64p3 rhs) { return new fix64p3 (lhs + rhs.x, lhs + rhs.y, lhs + rhs.z); }


        /// <summary>Returns the result of a componentwise subtraction operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator - (fix64p3 lhs, fix64p3 rhs) { return new fix64p3 (lhs.x - rhs.x, lhs.y - rhs.y, lhs.z - rhs.z); }

        /// <summary>Returns the result of a componentwise subtraction operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator - (fix64p3 lhs, fix64p rhs) { return new fix64p3 (lhs.x - rhs, lhs.y - rhs, lhs.z - rhs); }

        /// <summary>Returns the result of a componentwise subtraction operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator - (fix64p lhs, fix64p3 rhs) { return new fix64p3 (lhs - rhs.x, lhs - rhs.y, lhs - rhs.z); }


        /// <summary>Returns the result of a componentwise division operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator / (fix64p3 lhs, fix64p3 rhs) { return new fix64p3 (lhs.x / rhs.x, lhs.y / rhs.y, lhs.z / rhs.z); }

        /// <summary>Returns the result of a componentwise division operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator / (fix64p3 lhs, fix64p rhs) { return new fix64p3 (lhs.x / rhs, lhs.y / rhs, lhs.z / rhs); }

        /// <summary>Returns the result of a componentwise division operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator / (fix64p lhs, fix64p3 rhs) { return new fix64p3 (lhs / rhs.x, lhs / rhs.y, lhs / rhs.z); }


        /// <summary>Returns the result of a componentwise modulus operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator % (fix64p3 lhs, fix64p3 rhs) { return new fix64p3 (lhs.x % rhs.x, lhs.y % rhs.y, lhs.z % rhs.z); }

        /// <summary>Returns the result of a componentwise modulus operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator % (fix64p3 lhs, fix64p rhs) { return new fix64p3 (lhs.x % rhs, lhs.y % rhs, lhs.z % rhs); }

        /// <summary>Returns the result of a componentwise modulus operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator % (fix64p lhs, fix64p3 rhs) { return new fix64p3 (lhs % rhs.x, lhs % rhs.y, lhs % rhs.z); }


        /// <summary>Returns the result of a componentwise increment operation on a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator ++ (fix64p3 val) { return new fix64p3 (++val.x, ++val.y, ++val.z); }


        /// <summary>Returns the result of a componentwise decrement operation on a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator -- (fix64p3 val) { return new fix64p3 (--val.x, --val.y, --val.z); }


        /// <summary>Returns the result of a componentwise less than operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator < (fix64p3 lhs, fix64p3 rhs) { return new bool3 (lhs.x < rhs.x, lhs.y < rhs.y, lhs.z < rhs.z); }

        /// <summary>Returns the result of a componentwise less than operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator < (fix64p3 lhs, fix64p rhs) { return new bool3 (lhs.x < rhs, lhs.y < rhs, lhs.z < rhs); }

        /// <summary>Returns the result of a componentwise less than operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator < (fix64p lhs, fix64p3 rhs) { return new bool3 (lhs < rhs.x, lhs < rhs.y, lhs < rhs.z); }


        /// <summary>Returns the result of a componentwise less or equal operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator <= (fix64p3 lhs, fix64p3 rhs) { return new bool3 (lhs.x <= rhs.x, lhs.y <= rhs.y, lhs.z <= rhs.z); }

        /// <summary>Returns the result of a componentwise less or equal operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator <= (fix64p3 lhs, fix64p rhs) { return new bool3 (lhs.x <= rhs, lhs.y <= rhs, lhs.z <= rhs); }

        /// <summary>Returns the result of a componentwise less or equal operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator <= (fix64p lhs, fix64p3 rhs) { return new bool3 (lhs <= rhs.x, lhs <= rhs.y, lhs <= rhs.z); }


        /// <summary>Returns the result of a componentwise greater than operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator > (fix64p3 lhs, fix64p3 rhs) { return new bool3 (lhs.x > rhs.x, lhs.y > rhs.y, lhs.z > rhs.z); }

        /// <summary>Returns the result of a componentwise greater than operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator > (fix64p3 lhs, fix64p rhs) { return new bool3 (lhs.x > rhs, lhs.y > rhs, lhs.z > rhs); }

        /// <summary>Returns the result of a componentwise greater than operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator > (fix64p lhs, fix64p3 rhs) { return new bool3 (lhs > rhs.x, lhs > rhs.y, lhs > rhs.z); }


        /// <summary>Returns the result of a componentwise greater or equal operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator >= (fix64p3 lhs, fix64p3 rhs) { return new bool3 (lhs.x >= rhs.x, lhs.y >= rhs.y, lhs.z >= rhs.z); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator >= (fix64p3 lhs, fix64p rhs) { return new bool3 (lhs.x >= rhs, lhs.y >= rhs, lhs.z >= rhs); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator >= (fix64p lhs, fix64p3 rhs) { return new bool3 (lhs >= rhs.x, lhs >= rhs.y, lhs >= rhs.z); }


        /// <summary>Returns the result of a componentwise unary minus operation on a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator - (fix64p3 val) { return new fix64p3 (-val.x, -val.y, -val.z); }


        /// <summary>Returns the result of a componentwise unary plus operation on a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 operator + (fix64p3 val) { return new fix64p3 (+val.x, +val.y, +val.z); }


        /// <summary>Returns the result of a componentwise equality operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator == (fix64p3 lhs, fix64p3 rhs) { return new bool3 (lhs.x == rhs.x, lhs.y == rhs.y, lhs.z == rhs.z); }

        /// <summary>Returns the result of a componentwise equality operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator == (fix64p3 lhs, fix64p rhs) { return new bool3 (lhs.x == rhs, lhs.y == rhs, lhs.z == rhs); }

        /// <summary>Returns the result of a componentwise equality operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator == (fix64p lhs, fix64p3 rhs) { return new bool3 (lhs == rhs.x, lhs == rhs.y, lhs == rhs.z); }


        /// <summary>Returns the result of a componentwise not equal operation on two fix64p3 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator != (fix64p3 lhs, fix64p3 rhs) { return new bool3 (lhs.x != rhs.x, lhs.y != rhs.y, lhs.z != rhs.z); }

        /// <summary>Returns the result of a componentwise not equal operation on a fix64p3 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator != (fix64p3 lhs, fix64p rhs) { return new bool3 (lhs.x != rhs, lhs.y != rhs, lhs.z != rhs); }

        /// <summary>Returns the result of a componentwise not equal operation on a fix64p value and a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool3 operator != (fix64p lhs, fix64p3 rhs) { return new bool3 (lhs != rhs.x, lhs != rhs.y, lhs != rhs.z); }




        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, x, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, x, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xxxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, x, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, x, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, x, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xxyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, x, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xxzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, x, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xxzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, x, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xxzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, x, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, y, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, y, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xyxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, y, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, y, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, y, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xyyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, y, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xyzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, y, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xyzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, y, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xyzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, y, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xzxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, z, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xzxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, z, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xzxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, z, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xzyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, z, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xzyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, z, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xzyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, z, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xzzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, z, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xzzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, z, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 xzzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(x, z, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, x, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, x, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yxxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, x, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, x, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, x, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yxyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, x, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yxzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, x, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yxzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, x, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yxzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, x, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, y, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, y, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yyxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, y, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, y, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, y, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yyyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, y, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yyzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, y, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yyzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, y, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yyzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, y, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yzxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, z, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yzxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, z, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yzxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, z, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yzyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, z, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yzyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, z, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yzyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, z, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yzzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, z, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yzzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, z, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 yzzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(y, z, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zxxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, x, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zxxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, x, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zxxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, x, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zxyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, x, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zxyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, x, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zxyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, x, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zxzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, x, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zxzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, x, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zxzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, x, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zyxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, y, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zyxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, y, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zyxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, y, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zyyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, y, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zyyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, y, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zyyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, y, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zyzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, y, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zyzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, y, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zyzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, y, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zzxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, z, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zzxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, z, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zzxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, z, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zzyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, z, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zzyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, z, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zzyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, z, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zzzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, z, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zzzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, z, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p4 zzzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p4(z, z, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 xxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(x, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 xxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(x, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 xxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(x, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 xyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(x, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 xyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(x, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 xyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(x, y, z); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; y = value.y; z = value.z; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 xzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(x, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 xzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(x, z, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; z = value.y; y = value.z; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 xzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(x, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 yxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(y, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 yxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(y, x, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 yxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(y, x, z); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; x = value.y; z = value.z; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 yyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(y, y, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 yyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(y, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 yyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(y, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 yzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(y, z, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; z = value.y; x = value.z; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 yzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(y, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 yzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(y, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 zxx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(z, x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 zxy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(z, x, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { z = value.x; x = value.y; y = value.z; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 zxz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(z, x, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 zyx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(z, y, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { z = value.x; y = value.y; x = value.z; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 zyy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(z, y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 zyz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(z, y, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 zzx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(z, z, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 zzy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(z, z, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p3 zzz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p3(z, z, z); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p2 xx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p2(x, x); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p2 xy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p2(x, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; y = value.y; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p2 xz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p2(x, z); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { x = value.x; z = value.y; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p2 yx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p2(y, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; x = value.y; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p2 yy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p2(y, y); }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p2 yz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p2(y, z); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { y = value.x; z = value.y; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p2 zx
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p2(z, x); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { z = value.x; x = value.y; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p2 zy
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p2(z, y); }
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            set { z = value.x; y = value.y; }
        }


        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public fix64p2 zz
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get { return new fix64p2(z, z); }
        }



        /// <summary>Returns the fix64p element at a specified index.</summary>
        unsafe public fix64p this[int index]
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 3)
                    throw new System.ArgumentException("index must be between[0...2]");
#endif
                fixed (fix64p3* array = &this) { return ((fix64p*)array)[index]; }
            }
            set
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 3)
                    throw new System.ArgumentException("index must be between[0...2]");
#endif
                fixed (fix64p* array = &x) { array[index] = value; }
            }
        }

        /// <summary>Returns true if the fix64p3 is equal to a given fix64p3, false otherwise.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(fix64p3 rhs) { return x == rhs.x && y == rhs.y && z == rhs.z; }

        /// <summary>Returns true if the fix64p3 is equal to a given fix64p3, false otherwise.</summary>
        public override bool Equals(object o) { return Equals((fix64p3)o); }


        /// <summary>Returns a hash code for the fix64p3.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() { return (int)math.hash(this); }


        /// <summary>Returns a string representation of the fix64p3.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString()
        {
            return string.Format("fix64p3({0}, {1}, {2})", x, y, z);
        }

        /// <summary>Returns a string representation of the fix64p3 using a specified format and culture-specific format information.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Format("fix64p3({0}, {1}, {2})", x.ToString(format, formatProvider), y.ToString(format, formatProvider), z.ToString(format, formatProvider));
        }

        internal sealed class DebuggerProxy
        {
            public fix64p x;
            public fix64p y;
            public fix64p z;
            public DebuggerProxy(fix64p3 v)
            {
                x = v.x;
                y = v.y;
                z = v.z;
            }
        }

    }

    public static partial class math
    {
        /// <summary>Returns a fix64p3 vector constructed from three fix64p values.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 fix64p3(fix64p x, fix64p y, fix64p z) { return new fix64p3(x, y, z); }

        /// <summary>Returns a fix64p3 vector constructed from a fix64p value and a fix64p2 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 fix64p3(fix64p x, fix64p2 yz) { return new fix64p3(x, yz); }

        /// <summary>Returns a fix64p3 vector constructed from a fix64p2 vector and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 fix64p3(fix64p2 xy, fix64p z) { return new fix64p3(xy, z); }

        /// <summary>Returns a fix64p3 vector constructed from a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 fix64p3(fix64p3 xyz) { return new fix64p3(xyz); }

        /// <summary>Returns a fix64p3 vector constructed from a single fix64p value by assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 fix64p3(fix64p v) { return new fix64p3(v); }

        /// <summary>Returns a uint hash code of a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint hash(fix64p3 v)
        {
            return csum(fold_to_uint(v) * uint3(0x509B84C9u, 0x91D13847u, 0x52F7230Fu)) + 0xCF286E83u;
        }

        /// <summary>
        /// Returns a uint3 vector hash code of a fix64p3 vector.
        /// When multiple elements are to be hashes together, it can more efficient to calculate and combine wide hash
        /// that are only reduced to a narrow uint hash at the very end instead of at every step.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint3 hashwide(fix64p3 v)
        {
            return (fold_to_uint(v) * uint3(0xE121E6ADu, 0xC9CA1249u, 0x69B60C81u)) + 0xE0EB6C25u;
        }

        /// <summary>Returns the result of specified shuffling of the components from two fix64p3 vectors into a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p shuffle(fix64p3 a, fix64p3 b, ShuffleComponent x)
        {
            return select_shuffle_component(a, b, x);
        }

        /// <summary>Returns the result of specified shuffling of the components from two fix64p3 vectors into a fix64p2 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2 shuffle(fix64p3 a, fix64p3 b, ShuffleComponent x, ShuffleComponent y)
        {
            return fix64p2(
                select_shuffle_component(a, b, x),
                select_shuffle_component(a, b, y));
        }

        /// <summary>Returns the result of specified shuffling of the components from two fix64p3 vectors into a fix64p3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3 shuffle(fix64p3 a, fix64p3 b, ShuffleComponent x, ShuffleComponent y, ShuffleComponent z)
        {
            return fix64p3(
                select_shuffle_component(a, b, x),
                select_shuffle_component(a, b, y),
                select_shuffle_component(a, b, z));
        }

        /// <summary>Returns the result of specified shuffling of the components from two fix64p3 vectors into a fix64p4 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p4 shuffle(fix64p3 a, fix64p3 b, ShuffleComponent x, ShuffleComponent y, ShuffleComponent z, ShuffleComponent w)
        {
            return fix64p4(
                select_shuffle_component(a, b, x),
                select_shuffle_component(a, b, y),
                select_shuffle_component(a, b, z),
                select_shuffle_component(a, b, w));
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        internal static fix64p select_shuffle_component(fix64p3 a, fix64p3 b, ShuffleComponent component)
        {
            switch(component)
            {
                case ShuffleComponent.LeftX:
                    return a.x;
                case ShuffleComponent.LeftY:
                    return a.y;
                case ShuffleComponent.LeftZ:
                    return a.z;
                case ShuffleComponent.RightX:
                    return b.x;
                case ShuffleComponent.RightY:
                    return b.y;
                case ShuffleComponent.RightZ:
                    return b.z;
                default:
                    throw new System.ArgumentException("Invalid shuffle component: " + component);
            }
        }

    }
}
