//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.CompilerServices;

#pragma warning disable 0660, 0661

namespace Unity.Mathematics
{
    [System.Serializable]
    public partial struct fix64p2x3 : System.IEquatable<fix64p2x3>, IFormattable
    {
        public fix64p2 c0;
        public fix64p2 c1;
        public fix64p2 c2;

        /// <summary>fix64p2x3 zero value.</summary>
        public static readonly fix64p2x3 zero;

        /// <summary>Constructs a fix64p2x3 matrix from three fix64p2 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p2x3(fix64p2 c0, fix64p2 c1, fix64p2 c2)
        { 
            this.c0 = c0;
            this.c1 = c1;
            this.c2 = c2;
        }

        /// <summary>Constructs a fix64p2x3 matrix from 6 fix64p values given in row-major order.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p2x3(fix64p m00, fix64p m01, fix64p m02,
                         fix64p m10, fix64p m11, fix64p m12)
        { 
            this.c0 = new fix64p2(m00, m10);
            this.c1 = new fix64p2(m01, m11);
            this.c2 = new fix64p2(m02, m12);
        }

        /// <summary>Constructs a fix64p2x3 matrix from a single fix64p value by assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p2x3(fix64p v)
        {
            this.c0 = v;
            this.c1 = v;
            this.c2 = v;
        }

        /// <summary>Constructs a fix64p2x3 matrix from a single bool value by converting it to fix64p and assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p2x3(bool v)
        {
            this.c0 = math.select(new fix64p2(fix64p.zero), new fix64p2(fix64p.One), v);
            this.c1 = math.select(new fix64p2(fix64p.zero), new fix64p2(fix64p.One), v);
            this.c2 = math.select(new fix64p2(fix64p.zero), new fix64p2(fix64p.One), v);
        }

        /// <summary>Constructs a fix64p2x3 matrix from a bool2x3 matrix by componentwise conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p2x3(bool2x3 v)
        {
            this.c0 = math.select(new fix64p2(fix64p.zero), new fix64p2(fix64p.One), v.c0);
            this.c1 = math.select(new fix64p2(fix64p.zero), new fix64p2(fix64p.One), v.c1);
            this.c2 = math.select(new fix64p2(fix64p.zero), new fix64p2(fix64p.One), v.c2);
        }

        /// <summary>Constructs a fix64p2x3 matrix from a single int value by converting it to fix64p and assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p2x3(int v)
        {
            this.c0 = (fix64p2)v;
            this.c1 = (fix64p2)v;
            this.c2 = (fix64p2)v;
        }

        /// <summary>Constructs a fix64p2x3 matrix from a int2x3 matrix by componentwise conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p2x3(int2x3 v)
        {
            this.c0 = (fix64p2)v.c0;
            this.c1 = (fix64p2)v.c1;
            this.c2 = (fix64p2)v.c2;
        }

        /// <summary>Constructs a fix64p2x3 matrix from a single float value by converting it to fix64p and assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p2x3(float v)
        {
            this.c0 = (fix64p2)v;
            this.c1 = (fix64p2)v;
            this.c2 = (fix64p2)v;
        }

        /// <summary>Constructs a fix64p2x3 matrix from a float2x3 matrix by componentwise conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public fix64p2x3(float2x3 v)
        {
            this.c0 = (fix64p2)v.c0;
            this.c1 = (fix64p2)v.c1;
            this.c2 = (fix64p2)v.c2;
        }


        /// <summary>Implicitly converts a single fix64p value to a fix64p2x3 matrix by assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static implicit operator fix64p2x3(fix64p v) { return new fix64p2x3(v); }

        /// <summary>Explicitly converts a single bool value to a fix64p2x3 matrix by converting it to fix64p and assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator fix64p2x3(bool v) { return new fix64p2x3(v); }

        /// <summary>Explicitly converts a bool2x3 matrix to a fix64p2x3 matrix by componentwise conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator fix64p2x3(bool2x3 v) { return new fix64p2x3(v); }

        /// <summary>Explicitly converts a single int value to a fix64p2x3 matrix by converting it to fix64p and assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator fix64p2x3(int v) { return new fix64p2x3(v); }

        /// <summary>Explicitly converts a int2x3 matrix to a fix64p2x3 matrix by componentwise conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator fix64p2x3(int2x3 v) { return new fix64p2x3(v); }

        /// <summary>Explicitly converts a single float value to a fix64p2x3 matrix by converting it to fix64p and assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator fix64p2x3(float v) { return new fix64p2x3(v); }

        /// <summary>Explicitly converts a float2x3 matrix to a fix64p2x3 matrix by componentwise conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static explicit operator fix64p2x3(float2x3 v) { return new fix64p2x3(v); }


        /// <summary>Returns the result of a componentwise multiplication operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator * (fix64p2x3 lhs, fix64p2x3 rhs) { return new fix64p2x3 (lhs.c0 * rhs.c0, lhs.c1 * rhs.c1, lhs.c2 * rhs.c2); }

        /// <summary>Returns the result of a componentwise multiplication operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator * (fix64p2x3 lhs, fix64p rhs) { return new fix64p2x3 (lhs.c0 * rhs, lhs.c1 * rhs, lhs.c2 * rhs); }

        /// <summary>Returns the result of a componentwise multiplication operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator * (fix64p lhs, fix64p2x3 rhs) { return new fix64p2x3 (lhs * rhs.c0, lhs * rhs.c1, lhs * rhs.c2); }


        /// <summary>Returns the result of a componentwise addition operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator + (fix64p2x3 lhs, fix64p2x3 rhs) { return new fix64p2x3 (lhs.c0 + rhs.c0, lhs.c1 + rhs.c1, lhs.c2 + rhs.c2); }

        /// <summary>Returns the result of a componentwise addition operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator + (fix64p2x3 lhs, fix64p rhs) { return new fix64p2x3 (lhs.c0 + rhs, lhs.c1 + rhs, lhs.c2 + rhs); }

        /// <summary>Returns the result of a componentwise addition operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator + (fix64p lhs, fix64p2x3 rhs) { return new fix64p2x3 (lhs + rhs.c0, lhs + rhs.c1, lhs + rhs.c2); }


        /// <summary>Returns the result of a componentwise subtraction operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator - (fix64p2x3 lhs, fix64p2x3 rhs) { return new fix64p2x3 (lhs.c0 - rhs.c0, lhs.c1 - rhs.c1, lhs.c2 - rhs.c2); }

        /// <summary>Returns the result of a componentwise subtraction operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator - (fix64p2x3 lhs, fix64p rhs) { return new fix64p2x3 (lhs.c0 - rhs, lhs.c1 - rhs, lhs.c2 - rhs); }

        /// <summary>Returns the result of a componentwise subtraction operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator - (fix64p lhs, fix64p2x3 rhs) { return new fix64p2x3 (lhs - rhs.c0, lhs - rhs.c1, lhs - rhs.c2); }


        /// <summary>Returns the result of a componentwise division operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator / (fix64p2x3 lhs, fix64p2x3 rhs) { return new fix64p2x3 (lhs.c0 / rhs.c0, lhs.c1 / rhs.c1, lhs.c2 / rhs.c2); }

        /// <summary>Returns the result of a componentwise division operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator / (fix64p2x3 lhs, fix64p rhs) { return new fix64p2x3 (lhs.c0 / rhs, lhs.c1 / rhs, lhs.c2 / rhs); }

        /// <summary>Returns the result of a componentwise division operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator / (fix64p lhs, fix64p2x3 rhs) { return new fix64p2x3 (lhs / rhs.c0, lhs / rhs.c1, lhs / rhs.c2); }


        /// <summary>Returns the result of a componentwise modulus operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator % (fix64p2x3 lhs, fix64p2x3 rhs) { return new fix64p2x3 (lhs.c0 % rhs.c0, lhs.c1 % rhs.c1, lhs.c2 % rhs.c2); }

        /// <summary>Returns the result of a componentwise modulus operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator % (fix64p2x3 lhs, fix64p rhs) { return new fix64p2x3 (lhs.c0 % rhs, lhs.c1 % rhs, lhs.c2 % rhs); }

        /// <summary>Returns the result of a componentwise modulus operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator % (fix64p lhs, fix64p2x3 rhs) { return new fix64p2x3 (lhs % rhs.c0, lhs % rhs.c1, lhs % rhs.c2); }


        /// <summary>Returns the result of a componentwise increment operation on a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator ++ (fix64p2x3 val) { return new fix64p2x3 (++val.c0, ++val.c1, ++val.c2); }


        /// <summary>Returns the result of a componentwise decrement operation on a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator -- (fix64p2x3 val) { return new fix64p2x3 (--val.c0, --val.c1, --val.c2); }


        /// <summary>Returns the result of a componentwise less than operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator < (fix64p2x3 lhs, fix64p2x3 rhs) { return new bool2x3 (lhs.c0 < rhs.c0, lhs.c1 < rhs.c1, lhs.c2 < rhs.c2); }

        /// <summary>Returns the result of a componentwise less than operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator < (fix64p2x3 lhs, fix64p rhs) { return new bool2x3 (lhs.c0 < rhs, lhs.c1 < rhs, lhs.c2 < rhs); }

        /// <summary>Returns the result of a componentwise less than operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator < (fix64p lhs, fix64p2x3 rhs) { return new bool2x3 (lhs < rhs.c0, lhs < rhs.c1, lhs < rhs.c2); }


        /// <summary>Returns the result of a componentwise less or equal operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator <= (fix64p2x3 lhs, fix64p2x3 rhs) { return new bool2x3 (lhs.c0 <= rhs.c0, lhs.c1 <= rhs.c1, lhs.c2 <= rhs.c2); }

        /// <summary>Returns the result of a componentwise less or equal operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator <= (fix64p2x3 lhs, fix64p rhs) { return new bool2x3 (lhs.c0 <= rhs, lhs.c1 <= rhs, lhs.c2 <= rhs); }

        /// <summary>Returns the result of a componentwise less or equal operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator <= (fix64p lhs, fix64p2x3 rhs) { return new bool2x3 (lhs <= rhs.c0, lhs <= rhs.c1, lhs <= rhs.c2); }


        /// <summary>Returns the result of a componentwise greater than operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator > (fix64p2x3 lhs, fix64p2x3 rhs) { return new bool2x3 (lhs.c0 > rhs.c0, lhs.c1 > rhs.c1, lhs.c2 > rhs.c2); }

        /// <summary>Returns the result of a componentwise greater than operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator > (fix64p2x3 lhs, fix64p rhs) { return new bool2x3 (lhs.c0 > rhs, lhs.c1 > rhs, lhs.c2 > rhs); }

        /// <summary>Returns the result of a componentwise greater than operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator > (fix64p lhs, fix64p2x3 rhs) { return new bool2x3 (lhs > rhs.c0, lhs > rhs.c1, lhs > rhs.c2); }


        /// <summary>Returns the result of a componentwise greater or equal operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator >= (fix64p2x3 lhs, fix64p2x3 rhs) { return new bool2x3 (lhs.c0 >= rhs.c0, lhs.c1 >= rhs.c1, lhs.c2 >= rhs.c2); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator >= (fix64p2x3 lhs, fix64p rhs) { return new bool2x3 (lhs.c0 >= rhs, lhs.c1 >= rhs, lhs.c2 >= rhs); }

        /// <summary>Returns the result of a componentwise greater or equal operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator >= (fix64p lhs, fix64p2x3 rhs) { return new bool2x3 (lhs >= rhs.c0, lhs >= rhs.c1, lhs >= rhs.c2); }


        /// <summary>Returns the result of a componentwise unary minus operation on a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator - (fix64p2x3 val) { return new fix64p2x3 (-val.c0, -val.c1, -val.c2); }


        /// <summary>Returns the result of a componentwise unary plus operation on a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 operator + (fix64p2x3 val) { return new fix64p2x3 (+val.c0, +val.c1, +val.c2); }


        /// <summary>Returns the result of a componentwise equality operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator == (fix64p2x3 lhs, fix64p2x3 rhs) { return new bool2x3 (lhs.c0 == rhs.c0, lhs.c1 == rhs.c1, lhs.c2 == rhs.c2); }

        /// <summary>Returns the result of a componentwise equality operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator == (fix64p2x3 lhs, fix64p rhs) { return new bool2x3 (lhs.c0 == rhs, lhs.c1 == rhs, lhs.c2 == rhs); }

        /// <summary>Returns the result of a componentwise equality operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator == (fix64p lhs, fix64p2x3 rhs) { return new bool2x3 (lhs == rhs.c0, lhs == rhs.c1, lhs == rhs.c2); }


        /// <summary>Returns the result of a componentwise not equal operation on two fix64p2x3 matrices.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator != (fix64p2x3 lhs, fix64p2x3 rhs) { return new bool2x3 (lhs.c0 != rhs.c0, lhs.c1 != rhs.c1, lhs.c2 != rhs.c2); }

        /// <summary>Returns the result of a componentwise not equal operation on a fix64p2x3 matrix and a fix64p value.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator != (fix64p2x3 lhs, fix64p rhs) { return new bool2x3 (lhs.c0 != rhs, lhs.c1 != rhs, lhs.c2 != rhs); }

        /// <summary>Returns the result of a componentwise not equal operation on a fix64p value and a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool2x3 operator != (fix64p lhs, fix64p2x3 rhs) { return new bool2x3 (lhs != rhs.c0, lhs != rhs.c1, lhs != rhs.c2); }



        /// <summary>Returns the fix64p2 element at a specified index.</summary>
        unsafe public ref fix64p2 this[int index]
        {
            get
            {
#if ENABLE_UNITY_COLLECTIONS_CHECKS
                if ((uint)index >= 3)
                    throw new System.ArgumentException("index must be between[0...2]");
#endif
                fixed (fix64p2x3* array = &this) { return ref ((fix64p2*)array)[index]; }
            }
        }

        /// <summary>Returns true if the fix64p2x3 is equal to a given fix64p2x3, false otherwise.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool Equals(fix64p2x3 rhs) { return c0.Equals(rhs.c0) && c1.Equals(rhs.c1) && c2.Equals(rhs.c2); }

        /// <summary>Returns true if the fix64p2x3 is equal to a given fix64p2x3, false otherwise.</summary>
        public override bool Equals(object o) { return Equals((fix64p2x3)o); }


        /// <summary>Returns a hash code for the fix64p2x3.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override int GetHashCode() { return (int)math.hash(this); }


        /// <summary>Returns a string representation of the fix64p2x3.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public override string ToString()
        {
            return string.Format("fix64p2x3({0}, {1}, {2},  {3}, {4}, {5})", c0.x, c1.x, c2.x, c0.y, c1.y, c2.y);
        }

        /// <summary>Returns a string representation of the fix64p2x3 using a specified format and culture-specific format information.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public string ToString(string format, IFormatProvider formatProvider)
        {
            return string.Format("fix64p2x3({0}, {1}, {2},  {3}, {4}, {5})", c0.x.ToString(format, formatProvider), c1.x.ToString(format, formatProvider), c2.x.ToString(format, formatProvider), c0.y.ToString(format, formatProvider), c1.y.ToString(format, formatProvider), c2.y.ToString(format, formatProvider));
        }

    }

    public static partial class math
    {
        /// <summary>Returns a fix64p2x3 matrix constructed from three fix64p2 vectors.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 fix64p2x3(fix64p2 c0, fix64p2 c1, fix64p2 c2) { return new fix64p2x3(c0, c1, c2); }

        /// <summary>Returns a fix64p2x3 matrix constructed from from 6 fix64p values given in row-major order.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 fix64p2x3(fix64p m00, fix64p m01, fix64p m02,
                                          fix64p m10, fix64p m11, fix64p m12)
        {
            return new fix64p2x3(m00, m01, m02,
                                 m10, m11, m12);
        }

        /// <summary>Returns a fix64p2x3 matrix constructed from a single fix64p value by assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 fix64p2x3(fix64p v) { return new fix64p2x3(v); }

        /// <summary>Returns a fix64p2x3 matrix constructed from a single bool value by converting it to fix64p and assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 fix64p2x3(bool v) { return new fix64p2x3(v); }

        /// <summary>Return a fix64p2x3 matrix constructed from a bool2x3 matrix by componentwise conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 fix64p2x3(bool2x3 v) { return new fix64p2x3(v); }

        /// <summary>Returns a fix64p2x3 matrix constructed from a single int value by converting it to fix64p and assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 fix64p2x3(int v) { return new fix64p2x3(v); }

        /// <summary>Return a fix64p2x3 matrix constructed from a int2x3 matrix by componentwise conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 fix64p2x3(int2x3 v) { return new fix64p2x3(v); }

        /// <summary>Returns a fix64p2x3 matrix constructed from a single float value by converting it to fix64p and assigning it to every component.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 fix64p2x3(float v) { return new fix64p2x3(v); }

        /// <summary>Return a fix64p2x3 matrix constructed from a float2x3 matrix by componentwise conversion.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p2x3 fix64p2x3(float2x3 v) { return new fix64p2x3(v); }

        /// <summary>Return the fix64p3x2 transpose of a fix64p2x3 matrix.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static fix64p3x2 transpose(fix64p2x3 v)
        {
            return fix64p3x2(
                v.c0.x, v.c0.y,
                v.c1.x, v.c1.y,
                v.c2.x, v.c2.y);
        }

        /// <summary>Returns a uint hash code of a fix64p2x3 vector.</summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint hash(fix64p2x3 v)
        {
            return csum(fold_to_uint(v.c0) * uint2(0x93C30C2Bu, 0xDCAF0351u) + 
                        fold_to_uint(v.c1) * uint2(0x6E050B01u, 0x750FDBF5u) + 
                        fold_to_uint(v.c2) * uint2(0x7F3DD499u, 0x52EAAEBBu)) + 0x4599C793u;
        }

        /// <summary>
        /// Returns a uint2 vector hash code of a fix64p2x3 vector.
        /// When multiple elements are to be hashes together, it can more efficient to calculate and combine wide hash
        /// that are only reduced to a narrow uint hash at the very end instead of at every step.
        /// </summary>
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static uint2 hashwide(fix64p2x3 v)
        {
            return (fold_to_uint(v.c0) * uint2(0x83B5E729u, 0xC267163Fu) + 
                    fold_to_uint(v.c1) * uint2(0x67BC9149u, 0xAD7C5EC1u) + 
                    fold_to_uint(v.c2) * uint2(0x822A7D6Du, 0xB492BF15u)) + 0xD37220E3u;
        }

    }
}
